version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    image: mariadb
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inceptionNetwork
    ports:
      - 3306:3306
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html
    networks:
      - inceptionNetwork
    depends_on:
      - mariadb
      - redis
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./NGINX/
    image: nginx
    volumes:
      - wp:/var/www/html
    networks:
      - inceptionNetwork
    ports:
      - 443:443
      - 8081:8081
    depends_on:
      - wordpress
    restart: on-failure
  adminer:
    container_name: adminer
    build: ./bonus/adminer
    image: adminer
    restart: on-failure
    networks:
      - inceptionNetwork
    ports:
      - 8080:8080
  redis:
    container_name: redis
    build: ./bonus/redis
    image: redis
    restart: on-failure
    networks:
      - inceptionNetwork
    ports:
      - 6379:6379
  ftp:
    container_name: ftp
    build: ./bonus/ftp/
    image: ftp
    restart: on-failure
    volumes:
      - wp:/home/evblood/ftp/
    networks:
      - inceptionNetwork
    ports:
      - 40000-40005:40000-40005
      - "20:20"
      - "21:21"
    depends_on:
      - wordpress
  cadvisor:
    container_name: cadvisor
    build: ./bonus/cadvisor
    image: cadvisor
    restart: on-failure
    networks:
      - inceptionNetwork
    ports:
      - 2000:2000
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  staticwebsite:
    container_name: staticwebsite
    build: ./bonus/staticwebsite
    image: staticwebsite
    restart: on-failure
    networks:
      - inceptionNetwork
    ports:
      - 81:81

volumes:
  DB:
    driver_opts:
      o: bind
      device: /Users/sakllam/Desktop/data/mysql
  wp:
    driver_opts:
      o: bind
      device: /Users/sakllam/Desktop/data/wordpress
networks:
  inceptionNetwork:
      driver: bridge