FROM debian

#FROM debian <base image>

#ENV <set env>

# RUN ./scrypt.sh <run a cmd>

#COPY source dest #executes_in the host // copy files on my host inside cont image

#CMD >> executes an entrypoint [firstpart, secondpart]
